# Generated by Django 5.0.7 on 2024-07-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bargiri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_name', models.CharField(max_length=100)),
                ('F1_1', models.IntegerField(default=0)),
                ('F1_2', models.IntegerField(default=0)),
                ('F1_3', models.IntegerField(default=0)),
                ('F2_1', models.IntegerField(default=0)),
                ('F2_2', models.IntegerField(default=0)),
                ('F2_3', models.IntegerField(default=0)),
                ('F3_1', models.IntegerField(default=0)),
                ('F3_2', models.IntegerField(default=0)),
                ('F3_3', models.IntegerField(default=0)),
                ('F4_1', models.IntegerField(default=0)),
                ('F4_2', models.IntegerField(default=0)),
                ('F4_3', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
